---
- name: Install packages
  apt:
    pkg:
      - python3-pip
    update_cache: yes

- name: Install boto3
  pip:
    name: boto3

- name: Make directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    loop:
      - /opt/artemis/bin
      - /opt/artemis/data
