- hosts: localhost
  gather_facts: False
  vars:
    relay_chain_nodes:
      - name: relaychain-node-0
        zone: euw1-az1
      - name: relaychain-node-1
        zone: euw1-az2
    parachain_nodes:
      - name: parachain-node-0
        zone: euw1-az1
      - name: parachain-node-1
        zone: euw1-az2
      - name: parachain-node-2
        zone: euw1-az3
    keypair: rococo-keypair
    image_id: ami-01aa664a17515f5bb
    instance_type: t3a.medium

  tasks:
    - name: Create base security group
      amazon.aws.ec2_group:
        name: rococo-base-sg
        description: Node Security Group
        rules:
          - proto: icmp
            from_port: 8
            to_port: -1
            rule_desc: ICMP Echo Request
          - proto: tcp
            ports: 22
            cidr_ip: 0.0.0.0/0
            rule_desc: SSH
          - proto: tcp
            ports: 80
            cidr_ip: 0.0.0.0/0
            rule_desc: Certbot
        tags:
          Environment: rococo
      register: rococo_base_sg

    - name: Create substrate security group
      amazon.aws.ec2_group:
        name: rococo-substrate-sg
        description: Node Security Group
        rules:
          - proto: tcp
            ports: 30333
            group_name: rococo-substrate-sg
            rule_desc: Substrate P2P
          - proto: tcp
            ports: 9933
            cidr_ip: 0.0.0.0/0
            rule_desc: Substrate RPC
          - proto: tcp
            ports: 9944
            cidr_ip: 0.0.0.0/0
            rule_desc: Substrate WS
        tags:
          Environment: rococo
      register: rococo_substrate_sg

    - name: Create instances for relay chain
      community.aws.ec2_instance:
        key_name: rococo-keypair
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        security_groups:
          - "{{ rococo_base_sg.group_id }}"
          - "{{ rococo_substrate_sg.group_id }}"
        availability_zone: "{{ item.zone }}"
        network:
          assign_public_ip: true
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 64
              delete_on_termination: true
        ebs_optimized: yes
        wait: no
        name: "{{ item.name }}"
        tags:
          Environment: rococo
          Role: relaychain
      loop: "{{ relay_chain_nodes }}"

    - debug:
        msg: "{{ relay_chain_nodes }}"

    - name: create instances for parachain
      community.aws.ec2_instance:
        key_name: rococo-keypair
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        instance_role: "arn:aws:iam::232374692033:role/SnowforkEC2InstanceRococo"
        security_groups:
          - "{{ rococo_base_sg.group_id }}"
          - "{{ rococo_substrate_sg.group_id }}"
        availability_zone: "{{ item.zone }}"
        network:
          assign_public_ip: true
        volumes:
          - device_name: /dev/sda1
            ebs:
              volume_size: 64
              delete_on_termination: true
        ebs_optimized: yes
        wait: no
        name: "{{ item.name }}"
        tags:
          Environment: rococo
          Role: parachain
      loop: "{{ parachain_nodes }}"
