- hosts: parachain
  tasks:
    - name: Install packages
      apt:
        pkg:
          - python3-pip
        update_cache: yes

    - name: Install boto3
      pip:
        name: boto3

    - name: Make directories
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes
      loop:
        - /opt/artemis/bin
        - /opt/artemis/data

    - name: Download subkey
      amazon.aws.aws_s3:
        bucket: snowfork-rococo
        object: subkey
        dest: /usr/local/bin/subkey
        mode: get

    - name: Download collator
      amazon.aws.aws_s3:
        bucket: snowfork-rococo
        object: artemis-collator
        dest: /opt/artemis/bin/artemis-collator
        mode: get

    - name: Download Chainspec
      amazon.aws.aws_s3:
        bucket: snowfork-rococo
        object: rococo.json
        dest: /opt/artemis/rococo.json
        mode: get
