- hosts: parachain
  serial: 1
  vars:
    relaychain_bootnodes: "/ip4/{{ hostvars['relaychain-node-0'].private_ip_address }}/tcp/30333/p2p/{{ hostvars['relaychain-node-0'].peer_id }}"
    parachain_bootnodes: "/ip4/{{ hostvars['parachain-node-0'].private_ip_address }}/tcp/30333/p2p/{{ hostvars['parachain-node-0'].peer_id }}"

  tasks:
    - name: Create service file
      template:
        src: artemis-collator.service.j2
        dest: /etc/systemd/system/artemis-collator.service
        owner: root
        group: root
        mode: 0644
      vars:
        node_name: "node-{{ groups['parachain'].index(inventory_hostname) }}"
      notify: Restart collator

    - name: Make sure service is running
      systemd:
        name: artemis-collator
        state: started
        enabled: yes

  handlers:
    - name: Restart collator
      systemd:
        name: artemis-collator
        state: restarted
        daemon_reload: yes
