[package]
name = "artemis-core"
version = "0.1.1"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false }

[dev-dependencies]
hex = { package = "rustc-hex", version = "2.1.0", default-features = false }

[dependencies.frame-support]
default-features = false
git = "https://github.com/paritytech/substrate.git"
rev = "c9d93653e567f10867273b0171f3025419795c37"

[dependencies.sp-runtime]
default-features = false
git = "https://github.com/paritytech/substrate.git"
rev = "c9d93653e567f10867273b0171f3025419795c37"

[dependencies.sp-std]
default-features = false
git = "https://github.com/paritytech/substrate.git"
rev = "c9d93653e567f10867273b0171f3025419795c37"

[dependencies.sp-core]
default-features = false
git = "https://github.com/paritytech/substrate.git"
rev = "c9d93653e567f10867273b0171f3025419795c37"

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "sp-std/std",
    "sp-core/std",
    "sp-runtime/std",
]
