[package]
name = "artemis-xcm-support"
version = "0.1.0"
authors = ["Snowfork <contact@snowfork.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.5", default-features = false }

sp-std = { version = "2.0.0-rc5", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false}

frame-support = { git = "https://github.com/paritytech/substrate", branch = "rococo-branch", default-features = false}

xcm = { git = "https://github.com/paritytech/polkadot", branch = "gav-xcmp", default-features = false }
xcm-executor = { git = "https://github.com/paritytech/polkadot", branch = "gav-xcmp", default-features = false }

artemis-core = { path = "../../primitives/core", default-features = false }


[features]
default = ["std"]
std = [
        "sp-std/std",
        "sp-runtime/std",
        "frame-support/std",
        "xcm/std",
        "xcm-executor/std",
]
