[profile.release]
panic = "unwind"

[workspace]
members = [
    "primitives/core",
    "primitives/ethereum",
    "pallets/bridge",
    "pallets/asset",
    "pallets/verifier",
    "pallets/eth-app",
    "pallets/erc20-app",
    "pallets/parachain-info",
    "pallets/token-dealer",
    "node",
    "runtime",
]
