[package]
name = "artemis-runtime"
description = "Artemis Runtime"
version = "0.1.1"
edition = "2018"
authors = ["Snowfork <contact@snowfork.com>"]
repository = "https://github.com/Snowfork/polkadot-ethereum"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies.serde]
features = ["derive"]
optional = true
version = "1.0.101"

[dependencies.codec]
default-features = false
features = ["derive"]
package = "parity-scale-codec"
version = "1.3.4"

[dependencies.sp-std]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-api]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-io]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-version]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-runtime]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-core]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-session]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-offchain]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-block-builder]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-transaction-pool]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.sp-inherents]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"


[dependencies.frame-executive]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.frame-support]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.frame-system]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"


[dependencies.pallet-balances]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.pallet-randomness-collective-flip]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.pallet-timestamp]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"

[dependencies.pallet-transaction-payment]
default-features = false
git = "https://github.com/paritytech/substrate.git"
branch = "rococo-branch"


# Cumulus / XCMP

[dependencies.cumulus-runtime]
default-features = false
git = "https://github.com/paritytech/cumulus"
branch = "gav-xcmp"

[dependencies.cumulus-parachain-upgrade]
default-features = false
git = "https://github.com/paritytech/cumulus"
branch = "gav-xcmp"

[dependencies.cumulus-message-broker]
default-features = false
git = "https://github.com/paritytech/cumulus"
branch = "gav-xcmp"

[dependencies.parachain-info]
git = "https://github.com/paritytech/cumulus"
branch = "gav-xcmp"
default-features = false

[dependencies.cumulus-primitives]
default-features = false
git = "https://github.com/paritytech/cumulus"
branch = "gav-xcmp"


[dependencies.polkadot-parachain]
default-features = false
git = "https://github.com/paritytech/polkadot"
branch = "gav-xcmp"

# [dependencies.rococo-runtime]
# default-features = false
# git = "https://github.com/paritytech/polkadot"
# branch = "gav-xcmp"

[dependencies.xcm]
default-features = false
git = "https://github.com/paritytech/polkadot"
branch = "gav-xcmp"

[dependencies.xcm-executor]
default-features = false
git = "https://github.com/paritytech/polkadot"
branch = "gav-xcmp"

[dependencies.xcm-builder]
default-features = false
git = "https://github.com/paritytech/polkadot"
branch = "gav-xcmp"

[dependencies.pallet-xcm-handler]
default-features = false
git = "https://github.com/paritytech/polkadot"
branch = "gav-xcmp"



[build-dependencies.wasm-builder-runner]
package = "substrate-wasm-builder-runner"
version = "1.0.6"

# Our Pallets

[dependencies.artemis-xcm-support]
default-features = false
path = "../primitives/xcm-support"

[dependencies.bridge]
default-features = false
package = "pallet-bridge"
path = "../pallets/bridge"
version = "0.1.1"

[dependencies.verifier]
default-features = false
package = "pallet-verifier"
path = "../pallets/verifier"
version = "0.1.1"

[dependencies.assets]
default-features = false
package = "artemis-assets"
path = "../pallets/assets"
version = "0.1.1"

[dependencies.eth-app]
default-features = false
package = "artemis-eth-app"
path = "../pallets/eth-app"
version = "0.1.1"

[dependencies.erc20-app]
default-features = false
package = "artemis-erc20-app"
path = "../pallets/erc20-app"
version = "0.1.1"


[features]
default = ["std"]
std = [
    "codec/std",
    "serde",
    "sp-api/std",
    "sp-std/std",
    "sp-io/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-version/std",
    "sp-offchain/std",
    "sp-session/std",
    "sp-block-builder/std",
    "sp-transaction-pool/std",
    "sp-inherents/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-balances/std",
    "pallet-randomness-collective-flip/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
	"parachain-info/std",
	"cumulus-runtime/std",
	"cumulus-parachain-upgrade/std",
	"cumulus-message-broker/std",
#	"cumulus-upward-message/std",
	"cumulus-primitives/std",
    "parachain-info/std",
	"polkadot-parachain/std",
	"xcm/std",
	"xcm-executor/std",
	"xcm-builder/std",
	"pallet-xcm-handler/std",
    "artemis-xcm-support/std",
    "bridge/std",
    "verifier/std",
    "assets/std",
    "eth-app/std",
    "erc20-app/std",
]

#runtime-wasm = [
#	"cumulus-upward-message/runtime-wasm",
#]
